PREFIX = /usr/local/bin

DELICIOUS_SOURCE_FILE = Delicious.sh
DELICIOUS_SOURCE_PATH = $(CURDIR)/$(DELICIOUS_SOURCE_FILE)
DELICIOUS_TARGET_FILE = export_$(basename $(DELICIOUS_SOURCE_FILE))
DELICIOUS_TARGET_PATH = $(PREFIX)/$(DELICIOUS_TARGET_FILE)
$(DELICIOUS_TARGET_PATH): $(DELICIOUS_SOURCE_PATH)
	cp $(DELICIOUS_SOURCE_PATH) $(DELICIOUS_TARGET_PATH)

GOOGLE_AUTH_SOURCE_FILE = GoogleAuth.sh
GOOGLE_AUTH_SOURCE_PATH = $(CURDIR)/$(GOOGLE_AUTH_SOURCE_FILE)
GOOGLE_AUTH_TARGET_FILE = $(basename $(GOOGLE_AUTH_SOURCE_FILE))
GOOGLE_AUTH_TARGET_PATH = $(PREFIX)/$(GOOGLE_AUTH_TARGET_FILE)
$(GOOGLE_AUTH_TARGET_PATH): $(GOOGLE_AUTH_SOURCE_PATH)
	cp $(GOOGLE_AUTH_SOURCE_PATH) $(GOOGLE_AUTH_TARGET_PATH)

GOOGLE_CALENDAR_SOURCE_FILE = GoogleCalendar.sh
GOOGLE_CALENDAR_SOURCE_PATH = $(CURDIR)/$(GOOGLE_CALENDAR_SOURCE_FILE)
GOOGLE_CALENDAR_TARGET_FILE = export_$(basename $(GOOGLE_CALENDAR_SOURCE_FILE))
GOOGLE_CALENDAR_TARGET_PATH = $(PREFIX)/$(GOOGLE_CALENDAR_TARGET_FILE)
$(GOOGLE_CALENDAR_TARGET_PATH): $(GOOGLE_CALENDAR_SOURCE_PATH) $(GOOGLE_AUTH_TARGET_PATH)
	cp $(GOOGLE_CALENDAR_SOURCE_PATH) $(GOOGLE_CALENDAR_TARGET_PATH)

GOOGLE_READER_SOURCE_FILE = GoogleReader.sh
GOOGLE_READER_SOURCE_PATH = $(CURDIR)/$(GOOGLE_READER_SOURCE_FILE)
GOOGLE_READER_TARGET_FILE = export_$(basename $(GOOGLE_READER_SOURCE_FILE))
GOOGLE_READER_TARGET_PATH = $(PREFIX)/$(GOOGLE_READER_TARGET_FILE)
$(GOOGLE_READER_TARGET_PATH): $(GOOGLE_READER_SOURCE_PATH) $(GOOGLE_AUTH_TARGET_PATH)
	cp $(GOOGLE_READER_SOURCE_PATH) $(GOOGLE_READER_TARGET_PATH)

LAST_FM_SOURCE_FILE = last.fm.pl
LAST_FM_SOURCE_PATH = $(CURDIR)/$(LAST_FM_SOURCE_FILE)
LAST_FM_TARGET_FILE = export_$(basename $(LAST_FM_SOURCE_FILE))
LAST_FM_TARGET_PATH = $(PREFIX)/$(LAST_FM_TARGET_FILE)
$(LAST_FM_TARGET_PATH): $(LAST_FM_SOURCE_PATH)
	cp $(LAST_FM_SOURCE_PATH) $(LAST_FM_TARGET_PATH)

LIBRARYTHING_SOURCE_FILE = LibraryThing.sh
LIBRARYTHING_SOURCE_PATH = $(CURDIR)/$(LIBRARYTHING_SOURCE_FILE)
LIBRARYTHING_TARGET_FILE = export_$(basename $(LIBRARYTHING_SOURCE_FILE))
LIBRARYTHING_TARGET_PATH = $(PREFIX)/$(LIBRARYTHING_TARGET_FILE)
$(LIBRARYTHING_TARGET_PATH): $(LIBRARYTHING_SOURCE_PATH)
	cp $(LIBRARYTHING_SOURCE_PATH) $(LIBRARYTHING_TARGET_PATH)

WORDPRESS_COM_SOURCE_FILE = WordPress.com.sh
WORDPRESS_COM_SOURCE_PATH = $(CURDIR)/$(WORDPRESS_COM_SOURCE_FILE)
WORDPRESS_COM_TARGET_FILE = export_$(basename $(WORDPRESS_COM_SOURCE_FILE))
WORDPRESS_COM_TARGET_PATH = $(PREFIX)/$(WORDPRESS_COM_TARGET_FILE)
$(WORDPRESS_COM_TARGET_PATH): $(WORDPRESS_COM_SOURCE_PATH)
	cp $(WORDPRESS_COM_SOURCE_PATH) $(WORDPRESS_COM_TARGET_PATH)

# Static targets
.PHONY: install-delicious
install-delicious: $(DELICIOUS_TARGET_PATH)

.PHONY: install-google-calendar
install-google-calendar: $(GOOGLE_CALENDAR_TARGET_PATH)
	sed -i -e \
		"s/$(GOOGLE_AUTH_SOURCE_FILE)/$(GOOGLE_AUTH_TARGET_FILE)/g" \
		$(GOOGLE_CALENDAR_TARGET_PATH)

.PHONY: install-google-reader
install-google-reader: $(GOOGLE_READER_TARGET_PATH)
	sed -i -e \
		"s/$(GOOGLE_AUTH_SOURCE_FILE)/$(GOOGLE_AUTH_TARGET_FILE)/g" \
		$(GOOGLE_READER_TARGET_PATH)

.PHONY: install-last-fm
install-last-fm: $(LAST_FM_TARGET_PATH)

.PHONY: install-librarything
install-librarything: $(LIBRARYTHING_TARGET_PATH)

.PHONY: install-wordpress-com
install-wordpress-com: $(WORDPRESS_COM_TARGET_PATH)

.PHONY: install
install: \
	install-delicious \
	install-google-calendar \
	install-google-reader \
	install-last-fm \
	install-librarything \
	install-wordpress-com

.PHONY: uninstall
uninstall:
	rm -f \
		$(DELICIOUS_TARGET_PATH) \
		$(GOOGLE_AUTH_TARGET_PATH) \
		$(GOOGLE_CALENDAR_TARGET_PATH) \
		$(GOOGLE_READER_TARGET_PATH) \
		$(LAST_FM_TARGET_PATH) \
		$(LIBRARYTHING_TARGET_PATH) \
		$(WORDPRESS_COM_TARGET_PATH)

include tools.mk
